// <auto-generated />
namespace mvcEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db19));
        
        string IMigrationMetadata.Id
        {
            get { return "202001231623541_db19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
